/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ffAttestSol from "./ff-attest.sol";
export type { ffAttestSol };
import type * as ffClubSol from "./ff-club.sol";
export type { ffClubSol };
import type * as ffEventSol from "./ff-event.sol";
export type { ffEventSol };
import type * as ffGameSol from "./ff-game.sol";
export type { ffGameSol };
import type * as ffLeagueSol from "./ff-league.sol";
export type { ffLeagueSol };
import type * as ffLineupSol from "./ff-lineup.sol";
export type { ffLineupSol };
import type * as ffPlayerSol from "./ff-player.sol";
export type { ffPlayerSol };
import type * as ffRolesSol from "./ff-roles.sol";
export type { ffRolesSol };
import type * as ffViewsSol from "./ff-views.sol";
export type { ffViewsSol };
