/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace FFClub {
  export type ClubStruct = {
    id: BigNumberish;
    leagueId: BigNumberish;
    name: string;
    fixedGoalkeeper: boolean;
    owner: AddressLike;
  };

  export type ClubStructOutput = [
    id: bigint,
    leagueId: bigint,
    name: string,
    fixedGoalkeeper: boolean,
    owner: string
  ] & {
    id: bigint;
    leagueId: bigint;
    name: string;
    fixedGoalkeeper: boolean;
    owner: string;
  };
}

export interface FFClubInterface extends Interface {
  getFunction(
    nameOrSignature: "createClub" | "getClub" | "nextClubId" | "roles"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ClubCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createClub",
    values: [BigNumberish, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getClub",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextClubId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "roles", values?: undefined): string;

  decodeFunctionResult(functionFragment: "createClub", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getClub", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextClubId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "roles", data: BytesLike): Result;
}

export namespace ClubCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    leagueId: BigNumberish,
    name: string,
    fixedGoalkeeper: boolean,
    owner: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    leagueId: bigint,
    name: string,
    fixedGoalkeeper: boolean,
    owner: string
  ];
  export interface OutputObject {
    id: bigint;
    leagueId: bigint;
    name: string;
    fixedGoalkeeper: boolean;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FFClub extends BaseContract {
  connect(runner?: ContractRunner | null): FFClub;
  waitForDeployment(): Promise<this>;

  interface: FFClubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createClub: TypedContractMethod<
    [leagueId: BigNumberish, name: string, fixedGoalkeeper: boolean],
    [bigint],
    "nonpayable"
  >;

  getClub: TypedContractMethod<
    [clubId: BigNumberish],
    [FFClub.ClubStructOutput],
    "view"
  >;

  nextClubId: TypedContractMethod<[], [bigint], "view">;

  roles: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createClub"
  ): TypedContractMethod<
    [leagueId: BigNumberish, name: string, fixedGoalkeeper: boolean],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getClub"
  ): TypedContractMethod<
    [clubId: BigNumberish],
    [FFClub.ClubStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextClubId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "roles"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ClubCreated"
  ): TypedContractEvent<
    ClubCreatedEvent.InputTuple,
    ClubCreatedEvent.OutputTuple,
    ClubCreatedEvent.OutputObject
  >;

  filters: {
    "ClubCreated(uint256,uint256,string,bool,address)": TypedContractEvent<
      ClubCreatedEvent.InputTuple,
      ClubCreatedEvent.OutputTuple,
      ClubCreatedEvent.OutputObject
    >;
    ClubCreated: TypedContractEvent<
      ClubCreatedEvent.InputTuple,
      ClubCreatedEvent.OutputTuple,
      ClubCreatedEvent.OutputObject
    >;
  };
}
