/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IFFClub {
  export type ClubStruct = {
    id: BigNumberish;
    leagueId: BigNumberish;
    name: string;
    fixedGoalkeeper: boolean;
    owner: AddressLike;
  };

  export type ClubStructOutput = [
    id: bigint,
    leagueId: bigint,
    name: string,
    fixedGoalkeeper: boolean,
    owner: string
  ] & {
    id: bigint;
    leagueId: bigint;
    name: string;
    fixedGoalkeeper: boolean;
    owner: string;
  };
}

export interface IFFClubInterface extends Interface {
  getFunction(nameOrSignature: "getClub"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getClub",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getClub", data: BytesLike): Result;
}

export interface IFFClub extends BaseContract {
  connect(runner?: ContractRunner | null): IFFClub;
  waitForDeployment(): Promise<this>;

  interface: IFFClubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getClub: TypedContractMethod<
    [clubId: BigNumberish],
    [IFFClub.ClubStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getClub"
  ): TypedContractMethod<
    [clubId: BigNumberish],
    [IFFClub.ClubStructOutput],
    "view"
  >;

  filters: {};
}
