/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IFFGame {
  export type GameStruct = {
    id: BigNumberish;
    clubAId: BigNumberish;
    clubBId: BigNumberish;
    scheduledAt: BigNumberish;
    metadataCid: string;
    closed: boolean;
  };

  export type GameStructOutput = [
    id: bigint,
    clubAId: bigint,
    clubBId: bigint,
    scheduledAt: bigint,
    metadataCid: string,
    closed: boolean
  ] & {
    id: bigint;
    clubAId: bigint;
    clubBId: bigint;
    scheduledAt: bigint;
    metadataCid: string;
    closed: boolean;
  };
}

export interface IFFGameInterface extends Interface {
  getFunction(nameOrSignature: "getGame"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getGame",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
}

export interface IFFGame extends BaseContract {
  connect(runner?: ContractRunner | null): IFFGame;
  waitForDeployment(): Promise<this>;

  interface: IFFGameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getGame: TypedContractMethod<
    [gameId: BigNumberish],
    [IFFGame.GameStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [IFFGame.GameStructOutput],
    "view"
  >;

  filters: {};
}
