/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IFFLeague {
  export type LeagueStruct = {
    id: BigNumberish;
    name: string;
    location: string;
    category: string;
    owner: AddressLike;
    verificationLevel: BigNumberish;
  };

  export type LeagueStructOutput = [
    id: bigint,
    name: string,
    location: string,
    category: string,
    owner: string,
    verificationLevel: bigint
  ] & {
    id: bigint;
    name: string;
    location: string;
    category: string;
    owner: string;
    verificationLevel: bigint;
  };
}

export interface IFFLeagueInterface extends Interface {
  getFunction(nameOrSignature: "getLeague"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getLeague",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getLeague", data: BytesLike): Result;
}

export interface IFFLeague extends BaseContract {
  connect(runner?: ContractRunner | null): IFFLeague;
  waitForDeployment(): Promise<this>;

  interface: IFFLeagueInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLeague: TypedContractMethod<
    [leagueId: BigNumberish],
    [IFFLeague.LeagueStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLeague"
  ): TypedContractMethod<
    [leagueId: BigNumberish],
    [IFFLeague.LeagueStructOutput],
    "view"
  >;

  filters: {};
}
