/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IFFPlayer {
  export type PlayerStruct = {
    id: BigNumberish;
    account: AddressLike;
    fullName: string;
    nickname: string;
    primaryPosition: BigNumberish;
    secondaryPosition: BigNumberish;
    tertiaryPosition: BigNumberish;
    level: BigNumberish;
    isMinor: boolean;
    guardian: AddressLike;
    visibility: BigNumberish;
    clubId: BigNumberish;
  };

  export type PlayerStructOutput = [
    id: bigint,
    account: string,
    fullName: string,
    nickname: string,
    primaryPosition: bigint,
    secondaryPosition: bigint,
    tertiaryPosition: bigint,
    level: bigint,
    isMinor: boolean,
    guardian: string,
    visibility: bigint,
    clubId: bigint
  ] & {
    id: bigint;
    account: string;
    fullName: string;
    nickname: string;
    primaryPosition: bigint;
    secondaryPosition: bigint;
    tertiaryPosition: bigint;
    level: bigint;
    isMinor: boolean;
    guardian: string;
    visibility: bigint;
    clubId: bigint;
  };
}

export interface IFFPlayerInterface extends Interface {
  getFunction(nameOrSignature: "getPlayer"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPlayer",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getPlayer", data: BytesLike): Result;
}

export interface IFFPlayer extends BaseContract {
  connect(runner?: ContractRunner | null): IFFPlayer;
  waitForDeployment(): Promise<this>;

  interface: IFFPlayerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPlayer: TypedContractMethod<
    [playerId: BigNumberish],
    [IFFPlayer.PlayerStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPlayer"
  ): TypedContractMethod<
    [playerId: BigNumberish],
    [IFFPlayer.PlayerStructOutput],
    "view"
  >;

  filters: {};
}
