/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FFViews } from "./FFViews";
export type { IFFClub } from "./IFFClub";
export type { IFFEvent } from "./IFFEvent";
export type { IFFGame } from "./IFFGame";
export type { IFFLeague } from "./IFFLeague";
export type { IFFLineup } from "./IFFLineup";
export type { IFFPlayer } from "./IFFPlayer";
