/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ffAttestSol from "./ff-attest.sol";
export * as ffClubSol from "./ff-club.sol";
export * as ffEventSol from "./ff-event.sol";
export * as ffGameSol from "./ff-game.sol";
export * as ffLeagueSol from "./ff-league.sol";
export * as ffLineupSol from "./ff-lineup.sol";
export * as ffPlayerSol from "./ff-player.sol";
export * as ffRolesSol from "./ff-roles.sol";
export * as ffViewsSol from "./ff-views.sol";
