/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFFClub,
  IFFClubInterface,
} from "../../../contracts/ff-views.sol/IFFClub";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "clubId",
        type: "uint256",
      },
    ],
    name: "getClub",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "leagueId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "bool",
            name: "fixedGoalkeeper",
            type: "bool",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
        ],
        internalType: "struct IFFClub.Club",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFFClub__factory {
  static readonly abi = _abi;
  static createInterface(): IFFClubInterface {
    return new Interface(_abi) as IFFClubInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFFClub {
    return new Contract(address, _abi, runner) as unknown as IFFClub;
  }
}
