/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFFGame,
  IFFGameInterface,
} from "../../../contracts/ff-views.sol/IFFGame";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
    ],
    name: "getGame",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "clubAId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "clubBId",
            type: "uint256",
          },
          {
            internalType: "uint64",
            name: "scheduledAt",
            type: "uint64",
          },
          {
            internalType: "string",
            name: "metadataCid",
            type: "string",
          },
          {
            internalType: "bool",
            name: "closed",
            type: "bool",
          },
        ],
        internalType: "struct IFFGame.Game",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFFGame__factory {
  static readonly abi = _abi;
  static createInterface(): IFFGameInterface {
    return new Interface(_abi) as IFFGameInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFFGame {
    return new Contract(address, _abi, runner) as unknown as IFFGame;
  }
}
