/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFFLeague,
  IFFLeagueInterface,
} from "../../../contracts/ff-views.sol/IFFLeague";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "leagueId",
        type: "uint256",
      },
    ],
    name: "getLeague",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "location",
            type: "string",
          },
          {
            internalType: "string",
            name: "category",
            type: "string",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "uint8",
            name: "verificationLevel",
            type: "uint8",
          },
        ],
        internalType: "struct IFFLeague.League",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFFLeague__factory {
  static readonly abi = _abi;
  static createInterface(): IFFLeagueInterface {
    return new Interface(_abi) as IFFLeagueInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFFLeague {
    return new Contract(address, _abi, runner) as unknown as IFFLeague;
  }
}
