/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFFLineup,
  IFFLineupInterface,
} from "../../../contracts/ff-views.sol/IFFLineup";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "clubId",
        type: "uint256",
      },
    ],
    name: "getLineup",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFFLineup__factory {
  static readonly abi = _abi;
  static createInterface(): IFFLineupInterface {
    return new Interface(_abi) as IFFLineupInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFFLineup {
    return new Contract(address, _abi, runner) as unknown as IFFLineup;
  }
}
